### ISSUE TITLE
Add license to repository

### ISSUE THREAD

**Issue by Zoddo** [robvadai/ofxstatement-qif#1]
Hello,

Thanks for your work :)

I would like to publish a package for ofxstatement-qif to the [ArchLinux's User Repository](https://aur.archlinux.org/). However, this repository contains no license, which means the code is currently under full copyright restrictions (nobody has the legal right to distribute or even run your code).

Could you consider adding a license that allows using and redistributing your plugin's code to this repository?

**Comment by robvadai** [comment]
hi @Zoddo this is done

**Comment by Zoddo** [comment]
Thanks! :) 

I've published the [ofxstatement-qif](https://aur.archlinux.org/packages/ofxstatement-qif) package in the AUR.

**Comment by robvadai** [comment]
Good stuff, thanks for the contribution @Zoddo
